### ISSUE TITLE
Remove clipboard section from .profile

### ISSUE THREAD

**Issue by Slackadays** [willeccles/dotfiles#2]
I'm scouring GitHub for any and all mentions of `xclip`. I found in your dotfiles, there's [a section ](https://github.com/willeccles/dotfiles/blob/e50901020c0fdca7fa1769a4f18d38019d8ea191/base/.profile#L128) where `clipboard` is aliased to some `xclip` command. I wanted to suggest Clipboard, a project of mine (which actually uses C++!) that would let you purge that section completely and help make your dotfiles portable to macOS and Linux systems without xclip. It would also save you time because Clipboard can copy regular files and directories and only uses `cb` which is a full 7 characters less than `clipboard`. I hope my suggestion helps!

**Comment by sophec** [comment]
I don't use Linux, so I am happy to remove that section. However, I will not be using clipboard. Irrespective of the quality of the project (which I have not assessed), advertising your project to random people uninvited is not going to get you anywhere. If you make good software, users will come naturally, not through brute force. I hope this advice is useful in your future endeavors!

**Comment by Slackadays** [comment]
> advertising your project to random people uninvited is not going to get you anywhere. If you make good software, users will come naturally, not through brute force. I hope this advice is useful in your future endeavors!

I think although this is great advice, it's not the entire truth. The [others](https://github.com/emilknievel/dotfiles/issues/1) who I've [shared](https://github.com/ublue-os/boxkit/issues/21) Clipboard [with](https://github.com/exbotanical/dotfiles/issues/1) have [all](https://github.com/binyomen/dotfiles/issues/1) loved [it](https://github.com/leo-arch/clifm/issues/188), so I'm not sure where this bitterness is coming from. Either way, this kind of thing is important to do because although people will come naturally to good software, they can't come unless they know it exists.

**Comment by sophec** [comment]
I am not bitter, do not take this the wrong way. I just don't think it's worth my time or yours for me to be disingenuous. I would recommend taking a look at how many successful software authors did not go around advertising and instead spent that time focused on making good software. If I want a clipboard tool, I will search for one, and presumably find yours. However, I do not need one, and therefore do not appreciate the unwanted advertisement. Again, I do not have anything against you or your project, just the approach you've taken to get users. You don't really gain anything from people using your FOSS project, either, so it's probably not worth the effort you're putting into advertising it (though to be clear, I am not in charge of valuing your time--you are, and if you think this is worth your time, then absolutely feel free to ignore me!).

That said, I do not mean to discourage you from creating and maintaining software. It's a wonderful thing to do, and if you enjoy it, you should definitely continue! I would just refrain from doing this sort of thing as it has a bad smell and does not reflect well on you or your software. If you turn away Jehovah's witnesses who knock on your door, why would this be any different?

This is all food for thought and my opinions, of course. You do not have any duty to listen to me, but I also have no duty to use software that is advertised to me on my dotfiles repo of all things, and particularly that which would not fit my workflow.

**Comment by Slackadays** [comment]
I have a few things to work on, so this'll be my last comment. I like all you said because it's mostly true. The one thing where there might be trouble is with how many projects didn't go around advertising. Even though this sounds reasonable, it's the [just-world hypothesis](https://en.wikipedia.org/wiki/Just-world_hypothesis) in action. We'd love to think good software will get users naturally, but this could only happen in a meritocracy. Therefore, consider this thing I'm doing a kind of compensation because we don't live in a meritocracy. You couldn't count the number of awesome projects on GitHub that would be topping the charts in a meritocracy (where they get what they deserve) but are instead left to rot in the void of unstarred repos because they assumed they'd get what they deserved. We only see the popular ones because they got there by advertising or by luck.
